ocaml: use sysroot for dynamic libraries
Build are now failing on recently created containers using the
recommended Debian 8.11 environment for OCaml recipes producing
dynamic libraries.

All errors relate to the toolchain not finding the required c runtime
environment at different stages:

- ocaml-dbus ocamlc will use gcc without the sysroot compilation option:
| dbus_stubs.c:17:20: fatal error: string.h: No such file or directory
|  #include <string.h>
|                     ^
| compilation terminated.

- camomile does not pass the c-compiler flags down the chain, leading it
  to not find the cross-environment:
| ocamlopt.opt -noassert -I internal -I public -I toolslib -I . -o tools/parse_unidata.opt bigarray.cmxa str.cmxa toolslib.cmxa tools/parse_unidata.cmx
| [...]/camomile/0.8.5-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/6.4.0/ld: cannot find crt1.o: No such file or directory

- findlib will default to use the ld.conf file of the native
  environment.

Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>